### ISSUE TITLE
Trying to submit form with invalid fields should give more feedback

### ISSUE THREAD

**Issue by thomir** [canonical-ols/javan-rhino#155]
When filling out the payment form, if you enter an invalid credit card number, but fill everything else out, the "Add payment details" button becomes active. If you scroll down and click it, nothing happens. The "This is not a valid credit card number" hint under the credit card input widget isn't visible on the screen, so the user is left wondering what's happening.

I'm not a UI expert, but I can think of a few ways this might be improved:

1) Don't enable the "Add payment details" button if any of the form fields are invalid.
2) After the user clicks the "Add payment details" button, if any of the form fields are invalid add some red text close to the submit button saying "There are invalid form fields" (or similar).
3) Perhaps scroll the users browser window to show the invalid field.... actually, that sounds like a bad idea...

**Comment by earnubs** [comment]
The bug is 1, 2 is an enhancement for later, 3 is wontfix.

**Comment by katiefenn** [comment]
This only happens for me when I leave the credit card number field blank, not when I enter an invalid card number.

That being said, I believe the best solution is to provide a message at the bottom of the form (solution #2). Solution #1 is unworkable because "Add payment details" button becomes active when the "Terms and conditions" checkbox is checked, not when field values are valid. Solution #3 is unworkable because [scrolljacking is awful](https://www.sitepoint.com/scrolljacking-accessibility/)

**Comment by katiefenn** [comment]
I should also clarify that the "Add payment details" button is only disabled until the "terms and conditions" checkbox is checked. It is not linked to form validation, and this is intended.
