### ISSUE TITLE
header font-weight looks 300 in design

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/javan-rhino#57]
https://cloud.githubusercontent.com/assets/17748020/17519927/d2661076-5e45-11e6-95fa-eb2aa3d645a1.png looks like headers of weight 300, MU has 400

**Comment by bartaz** [comment]
We have 300 set in styles and this seems to be applied correctly:
https://github.com/canonical-ols/javan-rhino/blob/master/src/style/base.css#L63-L71

Fonts may look different then on designs, because we don't use Ubuntu web font, just native font (which don't include Ubuntu font on non-ubuntu systems).

**Comment by bartaz** [comment]
Fixed in #71
